language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

script:
  - cargo fmt --all -- --check
  - cargo build
  - cargo test
